#!/bin/csh -fe

if ( "$1" == "-h" || "$1" == "--help" || "$1" == "" ) then
  echo
  echo "greps: searches dspsr source code for regular expression"
  echo
  echo "usage:"
  echo "  greps <regex>"
  echo
  exit
endif

grep "$*" `find Kernel Signal -name "*.[hcC]"` `find Kernel Signal -name Makefile.am` `find Kernel Signal -name "*.cu"`

