#!/bin/sh

available_formats=`cd Kernel/Formats && echo */Makefile.am | sed -e 's|/Makefile.am||g'`

echo Available formats:

#
# Create an AC_DEFINE and AM_CONDITIONAL for each available format
#

echo "dnl Generated by bootstrap; do not edit" > config/bootstrap.m4
echo "AC_DEFUN([DSPSR_FORMATS]," >> config/bootstrap.m4
echo "[" >> config/bootstrap.m4
echo "  DSPSR_SELECTED_FORMATS([$available_formats])" >> config/bootstrap.m4

for format in $available_formats; do

  echo $format

  echo "DSPSR_TEST_FORMAT([${format}])" >> config/bootstrap.m4

  echo "AC_DEFINE([HAVE_${format}], [\$${format}_selected]," >> config/bootstrap.m4
  echo "          [Define to 1 to use the ${format} file format])" >> config/bootstrap.m4

  echo "AM_CONDITIONAL([HAVE_${format}], [test \$${format}_selected = 1])" >> config/bootstrap.m4

done

echo "])" >> config/bootstrap.m4

#
# Conditionally add SUBDIRS for each available format
#

echo "# Generated by bootstrap; do not edit" > config/Makefile.bootstrap
echo "SUBDIRS =" >> config/Makefile.bootstrap
echo "libFormats_la_LIBADD =" >> config/Makefile.bootstrap

for format in $available_formats; do

  echo "if HAVE_${format}" >> config/Makefile.bootstrap
  echo "  SUBDIRS += ${format}" >> config/Makefile.bootstrap
  echo "  libFormats_la_LIBADD += ${format}/lib${format}.la" >> config/Makefile.bootstrap
  echo "endif" >> config/Makefile.bootstrap

done

echo "SUBDIRS += ." >> config/Makefile.bootstrap

