//-*-C++-*-

/*

A ChannelOrder converts a BitSeries into a TimeSeries

Assumes within the BitStream dim varies most quickly, then pol, then chan, then time
This assumption is not specified anywhere else- only in instantiations generated by ChannelOrder and TimeOrder is this ordering assumed
nbit must be 32

*/

#ifndef __ChannelOrder_h
#define __ChannelOrder_h

#include "dsp/TimeSeries.h"
#include "dsp/BitSeries.h"
#include "dsp/Transformation.h"

namespace dsp {

  class ChannelOrder : public Transformation<BitSeries,TimeSeries> {

  public:

    //! Null constructor- always outofplace
    ChannelOrder();

    //! Destructor
    virtual ~ChannelOrder();

  protected:

    virtual void transformation ();
  };

}

#endif
